### ISSUE TITLE
林业科研

### ISSUE THREAD

**Issue by zjlovewy** [wuhongsheng/KMLQ#10]
1.菜单：林业科技支撑项目去掉
2.林业科技项目：柱状图标题：昆明市“十二五”以来林业科技项目实施情况统计
下面的文字去掉
3.表格不需要统计数据，按照附表25              昆明市“十二五”以来林业科技项目实施情况统计
把这个表做在这里。注意表头字段，很多都写错了，有的不是市区（县）
3.专业技术队伍，柱状图下面文字样式调整

**Comment by GaaraZhao** [comment]
该问题已解决
