### ISSUE TITLE
湿地

### ISSUE THREAD

**Issue by zjlovewy** [wuhongsheng/KMLQ#12]
1.在菜单上面加一个文字描述：（数字突出）
昆明湿地总面积约6.05万公顷，占全市国土面积的2.9%，占全省湿地面积的10.72%。其中，湖泊湿地类3.36万公顷，占全市湿地总面积的55.54％，河流湿地类面积1.23万公顷，占20.33％，沼泽湿地类0.03万公顷，占0.49％，人工湿地类1.43万公顷，占23.64％。
2.面积统计，柱状图标题：昆明市各县（市）区湿地面积情况统计，昆明市级的统计数据去掉，这里都是区县统计，表格加排序字段，柱状图下面文字调整
3.面积对比这个菜单里面的表格数据我没找到，这个数据在哪里来的，如果找不到就去掉
4.公园/保护区/林场/林业站，改为：公园/保护区/林场，
柱状图标题：省级以上自然保护区、森林公园、国有林场数量和面积情况统计
条件检索：（1）年份，（2）统计类型：自然保护区、森林公园、国有林场，（3）级别：县级、市级、省级、国家级
参照表格：柱状图横坐标：昆明市和云南省两个类型，现在的全国去掉
下面表格数据动态变化

**Comment by GaaraZhao** [comment]
该问题已解决
