### ISSUE TITLE
森林防火

### ISSUE THREAD

**Issue by zjlovewy** [wuhongsheng/KMLQ#13]
1.参照附表20                    2014-2015年昆明市森林防火情况统计，之前做的不要。
2,。柱状图标题：XX年昆明市森林防火情况统计
3.柱状图下面要加文字，如果选择的是2015年，下面第一条加上，如果选择2014年第一条不显示。
注：1、2015年统计数据不包含滇中新区（安宁市、嵩明县、官渡区大板桥）。
 2、扑火队伍数据包含森警队伍、市级消防直属大队、地方专业扑火队、季节性及半专业扑火队。

**Comment by GaaraZhao** [comment]
该问题已解决
