### ISSUE TITLE
林木种苗

### ISSUE THREAD

**Issue by zjlovewy** [wuhongsheng/KMLQ#15]
1。管理机构及良种使用情况，条件检索去掉，直接参照附表26    云南省地州（市）林木种苗管理机构及良种使用情况对比统计
柱状图加标题
2.苗木基地建设，参照附表12        昆明市各县（市）区2014-2015年苗木基地建设情况统计 ，筛选条件加年份，昆明市不参与统计，只是统计区县

**Comment by GaaraZhao** [comment]
该问题已解决
