### ISSUE TITLE
新增模块：林业改革

### ISSUE THREAD

**Issue by zjlovewy** [wuhongsheng/KMLQ#18]
分两个个部分：林权改革、国有林场改革、
1.林权改革
（1）文字描述：截至2016年，全市涉及林改面积1693.12万亩，已确权1667.02万亩，确权率98.46%，均山到户率95.2%。在已确权的集体林面积中，公益林1182.49万亩，商品林484.53万亩，商品林均山到户率90.5%。全市共发放《林权证》255737本，发证宗数403716宗，发证率99.5%。办理《林木权证》、《林下经济经营权证》抵押贷款3200万元。办理林权流转1603宗，流转面积25.01万亩，流转金额5.6亿元，林地流转平均价格为2246元/亩。办理林权抵押贷款698宗，抵押面积15.53万亩，贷款金额13.85亿元

（2）柱状图、表格：昆明市各县市区确权面积、使用类型面积、发放林权证情况
市区县	确权面积（万亩）	使用类型	发放林权证（万本）
		农户及经营者	%	集体统一经营	%	
安宁	130.69	34.54	26.4	96.15	73.6	3.00
呈贡	20.63	3.44	16.7	17.19	87.3	0.11
东川	146.43	43.51	29.7	102.92	70.3	1.66
富民	79.80	54.54	68.3	25.26	31.7	1.49
官渡	29.31	5.34	18.2	23.97	81.8	0.72
晋宁	115.71	42.45	36.7	73.26	63.3	0.77
禄劝	410.36	409.05	99.7	1.31	0.3	5.80
盘龙	79.67	8.83	11.1	70.84	88.9	0.35
石林	99.07	20.44	20.6	78.63	79.4	1.34
嵩明	51.43	29.14	56.7	22.29	43.3	0.68
五华	34.39	10.52	30.6	23.87	69.4	0.63
西山	62.94	18.09	28.7	44.85	71.3	0.49
寻甸	271.92	71.46	26.3	200.46	73.7	6.36.
宜良	130.33	62.66	48.1	67.67	51.9	2.11
2.国有林场改革
文字描述：（1）现状：昆明市所辖14个县市区范围内，共有国有林场14个，其中市级2个，县区12个。从经营类型上划分，全市国有林场均属生态公益型，经营总面积87.32万亩，森林面积63.78万亩，森林总蓄积量为199.55万立方米，森林覆盖率73.05%；
（2）目标：通过全面深化国有林场改革，切实做到“三增长、两建立、一确保”。即：资源增长、职工增收、林场增效；全面建立健全职工社会保障体系，尽快建立符合现代林业发展要求的国有林场管理体制和经营机制；确保林区社会和谐稳定

表格：国有林场统计
序号   林场       等级     所属地区
    1    西山林场   市级   西山
    2   海口林场   市级  西山
    3   方旺林场   区县级  官渡
    4   新村林场   区县级  东川
     5   二二二林场  区县级  东川
     6     法者林场      区县级  东川
     7      新城林场     区县级   呈贡
     8      麻大山林场  区县级  晋宁
     9      花园林场     区县级  宜良
     10     阳宗海林场  区县级  宜良
      11    禄丰村林场  区县级  宜良
     12     长松园林场  区县级  嵩明
     13     石林林场    区县级   石林
     14    旋涡塘林场    区县级  禄劝

**Comment by wuhongsheng** [comment]
已完成
