### ISSUE TITLE
待签收问题

### ISSUE THREAD

**Issue by zjlovewy** [wuhongsheng/KMLQ#20]
（1）用安宁市用户登录进去，看到一个未签收的行文，在WEB签收掉了，这边进去显示没有待签收的文件，但是上次那个被签收掉的文件还在。
（2）没有签收，不能预览行文，签收后，按钮“签收”两个字变成预览。点击预览行文正文。如果不是pdf，或者office格式，比如是rar格式，就下载，不能预览

**Comment by wuhongsheng** [comment]
已解决
