### ISSUE TITLE
营林绿化

### ISSUE THREAD

**Issue by zjlovewy** [wuhongsheng/KMLQ#4]
1.生态建设和绿化造林两个切换菜单分别改成：重点生态建设统计和绿化造林情况对比
2.在条件检索里面新增：项目类别：省级以上、市级。选择省级以上，增加检索：建设项目（参考附表6昆明市2014年～2015年各县区省级以上重点林业生态建设项目完成情况 ：天保、退耕还林.....），选择市级，去掉年份检索，展示附表5   “十二五”期间昆明市林业生态建设项目统计。
3.柱状图下面的文字去掉，在检索上面增加文字，绿化造林情况对比也是这个文字：（数字颜色突出）
“十二五”期间，全市林业生态建设市级以上总投入达26.16亿元，较“十一五” 10.9亿增长140%。累计共完成营造林面积31.67万公顷，完成量占全省营造林面积242.27万公顷的13.07%；义务植树7000万株，占全省总量的13.26%。
4.绿化造林情况
不用折线图，仍然和第一个一样用柱状图，横坐标区县，纵坐标数值，检索条件年份，下面的文字不要。
表格：市区（县）/造林株数（万株）/排序

**Comment by GaaraZhao** [comment]
该问题已解决
