### ISSUE TITLE
林业产业

### ISSUE THREAD

**Issue by zjlovewy** [wuhongsheng/KMLQ#8]
1.增加一个菜单放第一个：基本现状统计，柱状图表格形式，附表31 2015年全市林业产业基本现状统计，筛选条件年份
2.林业产值，数据表格：林业产值加单位（亿元），加排序，增加年份筛选
3.特色经济林也是一样，数据表格要加单位，表格第一个字段名错误，应该是名称，增加年份筛选
4.核桃产业不用折线图，还用柱状图，增加年份筛选，表格增加排序字段，横坐标区县，纵坐标值

**Comment by GaaraZhao** [comment]
该问题已解决
