### ISSUE TITLE
林下经济

### ISSUE THREAD

**Issue by zjlovewy** [wuhongsheng/KMLQ#9]
1.表格单位错误，应该是亿元，不是亿元/万元
2.州市对比，表格字段要按照附表28             云南省各地州（市）林下经济发展现状统计，柱状图值不用动 
2.区县对比，表格要严格按照附表32             昆明市林下经济发展现状统计    单位：万亩、万元、个、家、户，字段不能少（龙头企业2014年产值字段不要），柱状图值不用动

**Comment by GaaraZhao** [comment]
该问题已解决
